# Generated by Django 3.0.8 on 2020-08-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя куратора')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=30, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'Куратор',
                'verbose_name_plural': 'Кураторы',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20, verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=30, verbose_name='Порода')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paws.Kind', verbose_name='Вид')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('breed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paws.Breed')),
                ('nickname', models.CharField(max_length=30, verbose_name='Кличка')),
                ('age', models.SmallIntegerField(verbose_name='Возраст')),
                ('description', models.TextField(verbose_name='Описание')),
                ('title', models.CharField(max_length=50, verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, upload_to='animals/', verbose_name='Фотография')),
                ('status', models.CharField(choices=[('В приюте', 'Miss'), ('Обрёл дом', 'Home'), ('Неизвестно', 'Unknown')], default='Неизвестно', max_length=10, verbose_name='Статус')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paws.Curator', verbose_name='Куратор')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
            bases=('paws.breed',),
        ),
    ]
