# Generated by Django 3.0.8 on 2020-08-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'Порода', 'verbose_name_plural': 'Породы'},
        ),
    ]
