# Generated by Django 3.0.8 on 2020-08-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0002_auto_20200807_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('В приюте', 'В приюте'), ('Обрёл дом', 'Обрёл дом'), ('Неизвестно', 'Неизвестно')], default='Неизвестно', max_length=10, verbose_name='Статус'),
        ),
    ]
